networks:
  app-tier:
    driver: bridge

volumes:
  redis_data:
  db_data:
  # influxdb_data:

services:
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    restart: unless-stopped
    cpus: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 60
    networks:
      - app-tier
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=${KAFKA_CFG_NODE_ID}
      - KAFKA_CFG_PROCESS_ROLES=${KAFKA_CFG_PROCESS_ROLES}
      - KAFKA_CFG_LISTENERS=${KAFKA_CFG_LISTENERS}
      - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_CFG_ADVERTISED_LISTENERS}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      - ALLOW_PLAINTEXT_LISTENER=${ALLOW_PLAINTEXT_LISTENER}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
  
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    container_name: kafka-ui
    restart: unless-stopped
    cpus: 1
    ports:
      - "8080:8080"
    networks:
      - app-tier
    environment:
      - KAFKA_CLUSTERS_0_NAME=${KAFKA_CLUSTERS_0_NAME}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS}
    depends_on:
      kafka:
        condition: service_healthy

  opc-gateway:
    build: ./opc_gateway
    container_name: opc_gateway
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MODE=${MODE_OPC_GATEWAY}
      - OPC_ENDPOINT=${OPC_ENDPOINT}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID_OPC}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC_COMMANDS=${KAFKA_TOPIC_COMMANDS}
      - KAFKA_TOPIC_STATUS=${KAFKA_TOPIC_STATUS}
    volumes:
      - ./opc_gateway:/app
    depends_on:
      kafka:
        condition: service_healthy

  opc-gateway-status:
    build: ./opc_gateway
    container_name: opc_gateway-status
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MODE=${MODE_OPC_STATUS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - OPC_ENDPOINT=${OPC_ENDPOINT}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID_OPC}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC_STATUS=${KAFKA_TOPIC_STATUS}
    volumes:
      - ./opc_gateway:/app
    depends_on:
      kafka:
        condition: service_healthy

  postgres-db:
    image: postgres:17.5
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres-db
    networks:
      - app-tier

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC_COMMANDS=${KAFKA_TOPIC_COMMANDS}
      - KAFKA_TOPIC_STATUS=${KAFKA_TOPIC_STATUS}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID_BACKEND}
      - KAFKAJS_NO_PARTITIONER_WARNING=${KAFKAJS_NO_PARTITIONER_WARNING}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USER=${POSTGRES_USER}
      - DB_HOST=${POSTGRES_HOST}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_PORT=${POSTGRES_PORT}
    command: ["npm", "run", "dev"]
    depends_on:
      kafka:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/robot-app
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend/robot-app:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=${API_BASE_URL}
    command: sh -c "npm install && npm run dev -- --host"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  socket_command:
    build: ./socket_gateway
    container_name: socket_command
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MODE=command_listener
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC_COMMANDS=${KAFKA_TOPIC_COMMANDS}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID_SOCKET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./socket_gateway:/app
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  socket_status:
    build: ./socket_gateway
    container_name: socket_status
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MODE=status
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC_STATUS=${KAFKA_TOPIC_STATUS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - STATUS_INTERVAL=${STATUS_INTERVAL}
    volumes:
      - ./socket_gateway:/app
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  socket_coordinator:
    build: ./socket_gateway
    container_name: socket_coordinator
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MODE=coordinator
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC_STATUS=${KAFKA_TOPIC_STATUS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - STATUS_INTERVAL=${STATUS_INTERVAL}
    volumes:
      - ./socket_gateway:/app
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  socket_gateway_01:
    build: ./socket_gateway
    container_name: socket_gateway_01
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MODE=gateway_robot
      - ROBOT_ID=${BORUNTE_01_ID}
      - BORUNTE_IP=${BORUNTE_01_IP}
      - BORUNTE_PORT=${BORUNTE_01_SOCKET_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./socket_gateway:/app
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  # socket_gateway_02:
  #   build: ./socket_gateway
  #   container_name: socket_gateway_02
  #   network_mode: "host"
  #   #restart: always
  #   environment:
  #     - MODE=gateway_robot
  #     - ROBOT_ID=${BORUNTE_02_ID}
  #     - BORUNTE_IP=${BORUNTE_02_IP}
  #     - BORUNTE_PORT=${BORUNTE_02_SOCKET_PORT}
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
  #   volumes:
  #     - ./socket_gateway:/app
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
