modbus:
  mode: "tcp"            
  host: "190.168.10.108"   
  port: 5020              
  unit_id: 1             

  word_order: "high_low"   # "high_low" | "low_high"
  byte_order: "BIG"        # "big" | "little"

opc_nodes:               
  read:                  
    start_button:
      type: "method"
      name: "start_button"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 10, length: 1, dtype: "bool" }

    pause_button:
      type: "method"
      name: "pause_button"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 11, length: 1, dtype: "bool" }

    stop_button:
      type: "method"
      name: "stop_button"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 12, length: 1, dtype: "bool" }

    clear_alarm_button:
      type: "method"
      name: "clear_alarm_button"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 13, length: 1, dtype: "bool" }

    resume_button:
      type: "method"
      name: "resume_proceso_01"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 14, length: 1, dtype: "bool" }

    test_bit:
      type: "method"
      name: "proceso_03"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 15, length: 1, dtype: "bool" }

    jog_z:
      type: "method"
      name: "proceso_04"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 16, length: 1, dtype: "bool" }

    standby:
      type: "method"
      name: "proceso_05"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 17, length: 1, dtype: "bool" }

    gripper_off:
      type: "method"
      name: "proceso_06"
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 18, length: 1, dtype: "bool" }

    send_data:
      type: "proceso"
      name: "send_data" 
      debounce_ms: 50
      modbus: { kind: "coil", fc: 1, addr: 19, length: 1, dtype: "bool" }
    
    bit_stack:
      type: "bridge"
      name: "modify_output_y"
      debounce_ms: 50
      param: { output_id: "42", value: false }
      modbus: { kind: "coil", fc: 1, addr: 61, length: 1, dtype: "bool" }

    long_caja:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 10, length: 1, dtype: "uint16" }

    ancho_caja:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 11, length: 1, dtype: "uint16" }

    altura_caja:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 12, length: 1, dtype: "uint16" }

    long_barra:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 13, length: 1, dtype: "uint16" }

    ancho_barra:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 14, length: 1, dtype: "uint16" }

    espesor:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 15, length: 1, dtype: "uint16" }

    peso:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 16, length: 1, dtype: "uint16" }

    cantidad_x:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 17, length: 1, dtype: "uint16" }

    cantidad_z:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 18, length: 1, dtype: "uint16" }

    no_carro:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 19, length: 1, dtype: "uint16" }

    w1:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 20, length: 1, dtype: "uint16" }

    w2:
      type: "data"
      val: 0
      modbus: { kind: "holding", fc: 3, addr: 21, length: 1, dtype: "uint16" }

  write:
    robot1:
      state_green:      { kind: "holding", fc: 6, addr: 100, dtype: "uint16" }
      state_yellow:    { kind: "holding", fc: 6, addr: 101, dtype: "uint16" }
      state_red:     { kind: "holding", fc: 6, addr: 102, dtype: "uint16" }
      running:        { kind: "holding", fc: 6, addr: 103, dtype: "uint16" }
      terminado:      { kind: "holding", fc: 6, addr: 104, dtype: "uint16" }
      set_ok:         { kind: "holding", fc: 6, addr: 105, dtype: "uint16" }
      stack_count:    { kind: "holding", fc: 6, addr: 106, dtype: "uint16" }     
      stack_ready:    { kind: "holding", fc: 6, addr: 107, dtype: "uint16" }
      layer_ready:    { kind: "holding", fc: 6, addr: 108, dtype: "uint16" }
      gripper_state:  { kind: "holding", fc: 6, addr: 109, dtype: "uint16" }
      alarm_code:     { kind: "holding", fc: 6, addr: 110, dtype: "uint16" }

      pos_x:          { kind: "holding", fc: 16, addr: 150, dtype: "int16" }     
      pos_y:          { kind: "holding", fc: 16, addr: 151, dtype: "int16" }
      pos_z:          { kind: "holding", fc: 16, addr: 152, dtype: "int16" }
      ang_u:          { kind: "holding", fc: 16, addr: 153, dtype: "int16" }
      ang_v:          { kind: "holding", fc: 16, addr: 154, dtype: "int16" }
      ang_w:          { kind: "holding", fc: 16, addr: 155, dtype: "int16" }
      j1:             { kind: "holding", fc: 16, addr: 156, dtype: "int16" }
      j2:             { kind: "holding", fc: 16, addr: 157, dtype: "int16" }
      j3:             { kind: "holding", fc: 16, addr: 158, dtype: "int16" }
      j4:             { kind: "holding", fc: 16, addr: 159, dtype: "int16" }
      j5:             { kind: "holding", fc: 16, addr: 160, dtype: "int16" }
      j6:             { kind: "holding", fc: 16, addr: 161, dtype: "int16" }

    robot2:
      state_green:      { kind: "holding", fc: 6, addr: 200, dtype: "uint16" }
      state_yellow:    { kind: "holding", fc: 6, addr: 201, dtype: "uint16" }
      state_red:     { kind: "holding", fc: 6, addr: 202, dtype: "uint16" }
      running:        { kind: "holding", fc: 6, addr: 203, dtype: "uint16" }
      terminado:      { kind: "holding", fc: 6, addr: 204, dtype: "uint16" }
      set_ok:         { kind: "holding", fc: 6, addr: 205, dtype: "uint16" }
      stack_count:    { kind: "holding", fc: 6, addr: 206, dtype: "uint16" }     
      stack_ready:    { kind: "holding", fc: 6, addr: 207, dtype: "uint16" }
      layer_ready:    { kind: "holding", fc: 6, addr: 208, dtype: "uint16" }
      gripper_state:  { kind: "holding", fc: 6, addr: 209, dtype: "uint16" }
      alarm_code:     { kind: "holding", fc: 6, addr: 210, dtype: "uint16" }
  
      pos_x:          { kind: "holding", fc: 16, addr: 250, dtype: "int16" }
      pos_y:          { kind: "holding", fc: 16, addr: 251, dtype: "int16" }
      pos_z:          { kind: "holding", fc: 16, addr: 252, dtype: "int16" }
      ang_u:          { kind: "holding", fc: 16, addr: 253, dtype: "int16" }
      ang_v:          { kind: "holding", fc: 16, addr: 254, dtype: "int16" }
      ang_w:          { kind: "holding", fc: 16, addr: 255, dtype: "int16" }
      j1:             { kind: "holding", fc: 16, addr: 256, dtype: "int16" }
      j2:             { kind: "holding", fc: 16, addr: 257, dtype: "int16" }
      j3:             { kind: "holding", fc: 16, addr: 258, dtype: "int16" }
      j4:             { kind: "holding", fc: 16, addr: 259, dtype: "int16" }
      j5:             { kind: "holding", fc: 16, addr: 260, dtype: "int16" }
      j6:             { kind: "holding", fc: 16, addr: 261, dtype: "int16" }