modbus:
  mode: "tcp"            
  host: "190.168.10.106"   
  port: 5020              
  unit_id: 1             

  word_order: "high_low"   # "high_low" | "low_high"
  byte_order: "BIG"        # "big" | "little"

opc_nodes:
  read:
    start_button:
      type: "method"
      name: "start_button" 
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 0, dtype: "uint16" }   # CTW.bit0

    pause_button:
      type: "bridge"
      name: "pause_button"
      debounce_ms: 50
      param: { value: false }
      modbus: { kind: "holding", addr: 39, bit: 2, dtype: "uint16" }   # CTW.bit1

    stop_button:
      type: "method"
      name: "stop_button"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 1, dtype: "uint16" }   # CTW.bit2

    clear_alarm_button:
      type: "method"
      name: "clear_alarm_button"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 3, dtype: "uint16" }   # CTW.bit3

    bit_stack:
      type: "bridge"
      name: "modify_output_y"
      debounce_ms: 50
      param: { output_id: "42", value: false }
      modbus: { kind: "holding", addr: 39, bit: 4, dtype: "uint16" }   # CTW.bit3

    resume_button:
      type: "method"
      name: "resume_proceso_01"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 10, dtype: "uint16" }   # CTW.bit4

    send_data:
      type: "proceso"
      name: "send_data"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 9, dtype: "uint16" }   # CTW.bit6 (ejemplo)
    
    test:
      type: "method"
      name: "proceso_03"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 5, dtype: "uint16" }   # CTW.bit6 (ejemplo)    
    
    jog_z:
      type: "method"
      name: "proceso_04"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 6, dtype: "uint16" }   # CTW.bit6 (ejemplo)
    
    home:
      type: "method"
      name: "proceso_05"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 7, dtype: "uint16" }   # CTW.bit6 (ejemplo)
    
    gripper_off:
      type: "method"
      name: "proceso_06"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 8, dtype: "uint16" }   # CTW.bit6 (ejemplo)
    
    cancel_button:
      type: "method"
      name: "cancel_button"
      debounce_ms: 50
      modbus: { kind: "holding", addr: 39, bit: 11, dtype: "uint16" }   # CTW.bit6 (ejemplo)

    # data (float32)
    ancho_barra:  { type: "data", modbus: { kind: "holding", fc: 3, addr: 40,  length: 2, dtype: "float32" } }
    long_barra:   { type: "data", modbus: { kind: "holding", fc: 3, addr: 42,  length: 2, dtype: "float32" } }
    espesor:      { type: "data", modbus: { kind: "holding", fc: 3, addr: 44,  length: 2, dtype: "float32" } }
    peso:         { type: "data", modbus: { kind: "holding", fc: 3, addr: 46,  length: 2, dtype: "float32" } }
    ancho_caja:   { type: "data", modbus: { kind: "holding", fc: 3, addr: 48,  length: 2, dtype: "float32" } }
    long_caja:    { type: "data", modbus: { kind: "holding", fc: 3, addr: 50, length: 2, dtype: "float32" } }
    altura_caja:  { type: "data", modbus: { kind: "holding", fc: 3, addr: 52, length: 2, dtype: "float32" } }
    # desfase y
    w1:           { type: "data", modbus: { kind: "holding", fc: 3, addr: 54, length: 1, dtype: "int16"   } }
    # libre para uso
    w2:           { type: "data", modbus: { kind: "holding", fc: 3, addr: 54, length: 1, dtype: "int16"   } }
    cantidad_x:   { type: "data", modbus: { kind: "holding", fc: 3, addr: 55, length: 1, dtype: "int16"   } }
    cantidad_z:   { type: "data", modbus: { kind: "holding", fc: 3, addr: 56, length: 1, dtype: "int16"   } }
    no_carro:     { type: "data", modbus: { kind: "holding", fc: 3, addr: 57, length: 1, dtype: "int16"   } }
  write:
    robot1:
      # STW bits (rellena los bit IDs correctos)
      running:        { kind: "holding", addr: 0, bit: 0, dtype: "uint16" }
      state_green:    { kind: "holding", addr: 0, bit: 1, dtype: "uint16" }
      state_red:      { kind: "holding", addr: 0, bit: 2, dtype: "uint16" }
      state_yellow:   { kind: "holding", addr: 0, bit: 3, dtype: "uint16" }
      stack_ready:    { kind: "holding", addr: 0, bit: 4, dtype: "uint16" }
      terminado:      { kind: "holding", addr: 0, bit: 5, dtype: "uint16" }
      layer_ready:    { kind: "holding", addr: 0, bit: 6, dtype: "uint16" }
      home_done:      { kind: "holding", addr: 0, bit: 7, dtype: "uint16" }
      # Respuesta de grabado de datos
      set_ok:         { kind: "holding", addr: 0, bit: 7, dtype: "uint16" }
      gripper_state:  { kind: "holding", addr: 0, bit: 8, dtype: "uint16" }

      alarm_code:     { kind: "holding", addr: 1, dtype: "int16" }
      stack_count:    { kind: "holding", addr: 2, dtype: "int16" }
      stack_time:     { kind: "holding", addr: 3, dtype: "int16" }

      pos_x: { kind: "holding", addr: 4,  dtype: "float32" }
      pos_y: { kind: "holding", addr: 6,  dtype: "float32" }
      pos_z: { kind: "holding", addr: 8,  dtype: "float32" }
      ang_u: { kind: "holding", addr: 10, dtype: "float32" }
      ang_v: { kind: "holding", addr: 12, dtype: "float32" }
      ang_w: { kind: "holding", addr: 14, dtype: "float32" }

      j1: { kind: "holding", addr: 16, dtype: "float32" }
      j2: { kind: "holding", addr: 18, dtype: "float32" }
      j3: { kind: "holding", addr: 20, dtype: "float32" }
      j4: { kind: "holding", addr: 22, dtype: "float32" }
      j5: { kind: "holding", addr: 24, dtype: "float32" }
      j6: { kind: "holding", addr: 26, dtype: "float32" }

    robot2:
      state_green:      { kind: "holding", fc: 6, addr: 200, dtype: "uint16" }
      state_yellow:    { kind: "holding", fc: 6, addr: 201, dtype: "uint16" }
      state_red:     { kind: "holding", fc: 6, addr: 202, dtype: "uint16" }
      running:        { kind: "holding", fc: 6, addr: 203, dtype: "uint16" }
      terminado:      { kind: "holding", fc: 6, addr: 204, dtype: "uint16" }
      set_ok:         { kind: "holding", fc: 6, addr: 205, dtype: "uint16" }
      stack_count:    { kind: "holding", fc: 6, addr: 206, dtype: "uint16" }     
      stack_ready:    { kind: "holding", fc: 6, addr: 207, dtype: "uint16" }
      layer_ready:    { kind: "holding", fc: 6, addr: 208, dtype: "uint16" }
      gripper_state:  { kind: "holding", fc: 6, addr: 209, dtype: "uint16" }
      alarm_code:     { kind: "holding", fc: 6, addr: 210, dtype: "uint16" }
  
      pos_x:          { kind: "holding", fc: 16, addr: 250, dtype: "int16" }
      pos_y:          { kind: "holding", fc: 16, addr: 251, dtype: "int16" }
      pos_z:          { kind: "holding", fc: 16, addr: 252, dtype: "int16" }
      ang_u:          { kind: "holding", fc: 16, addr: 253, dtype: "int16" }
      ang_v:          { kind: "holding", fc: 16, addr: 254, dtype: "int16" }
      ang_w:          { kind: "holding", fc: 16, addr: 255, dtype: "int16" }
      j1:             { kind: "holding", fc: 16, addr: 256, dtype: "int16" }
      j2:             { kind: "holding", fc: 16, addr: 257, dtype: "int16" }
      j3:             { kind: "holding", fc: 16, addr: 258, dtype: "int16" }
      j4:             { kind: "holding", fc: 16, addr: 259, dtype: "int16" }
      j5:             { kind: "holding", fc: 16, addr: 260, dtype: "int16" }
      j6:             { kind: "holding", fc: 16, addr: 261, dtype: "int16" }