opc_nodes:
  read:   # SOLO lectura
    start_button:
      type: "method"
      name: "start_button"
      kind: coil        # comando => coil
      unit: 1
      addr: 50

    pause_button:
      type: "method"
      name: "pause_button"
      kind: coil
      unit: 1
      addr: 51

    stop_button:
      type: "method"
      name: "stop_button"
      kind: coil
      unit: 1
      addr: 52

    clear_alarm_button:
      type: "method"
      name: "clear_alarm_button"
      kind: coil
      unit: 1
      addr: 53

    resume_button:
      type: "method"
      name: "resume_proceso_01"
      kind: coil
      unit: 1
      addr: 54

    test_bit:
      type: "method"
      name: "proceso_03"
      kind: coil
      unit: 1
      addr: 55

    jog_z:
      type: "method"
      name: "proceso_04"
      kind: coil
      unit: 1
      addr: 56

    standby:
      type: "method"
      name: "proceso_05"
      kind: coil
      unit: 1
      addr: 57

    gripper_off:
      type: "method"
      name: "proceso_06"
      kind: coil
      unit: 1
      addr: 58

    send_data:
      type: "proceso"
      kind: coil
      unit: 1
      addr: 59

    long_caja:
      type: "data"
      unit: 1
      addr: 10       # holding (por defecto)
      dtype: uint16

    ancho_caja:
      type: "data"
      unit: 1
      addr: 11
      dtype: uint16

    altura_caja:
      type: "data"
      unit: 1
      addr: 12
      dtype: uint16

    long_barra:
      type: "data"
      unit: 1
      addr: 13
      dtype: uint16

    ancho_barra:
      type: "data"
      unit: 1
      addr: 14
      dtype: uint16

    espesor:
      type: "data"
      unit: 1
      addr: 15
      dtype: uint16

    peso:
      type: "data"
      unit: 1
      addr: 16
      dtype: uint16

    cantidad_x:
      type: "data"
      unit: 1
      addr: 17
      dtype: uint16

    cantidad_z:
      type: "data"
      unit: 1
      addr: 18
      dtype: uint16

    no_carro:
      type: "data"
      unit: 1
      addr: 19
      dtype: uint16

    w1:
      type: "data"
      unit: 1
      addr: 20
      dtype: uint16

    w2:
      type: "data"
      unit: 1
      addr: 21
      dtype: uint16

    bit_stack:
      type: "bridge"
      name: "modify_output_y"
      param: { output_id: "42", value: false }
      kind: coil
      unit: 1
      addr: 50

  write:  # Escritura + confirmación de lectura
    robot1:
      running:        { unit: 1, addr: 76, dtype: uint16, confirm: true }
      terminado:      { unit: 1, addr: 81, dtype: uint16, confirm: true }
      set_ok:         { unit: 1, addr: 85, dtype: uint16, confirm: true }
      stack_count:    { unit: 1, addr: 42, dtype: uint16, confirm: true }
      stack_ready:    { unit: 1, addr: 80, dtype: uint16, confirm: true }
      layer_ready:    { unit: 1, addr: 82, dtype: uint16, confirm: true }
      gripper_state:  { unit: 1, addr: 84, dtype: uint16, confirm: true }
      alarm_code:     { unit: 1, addr: 83, dtype: uint16, confirm: true }

      pos_x: { unit: 1, addr: 47, dtype: int32,  confirm: true }  # 2 registros
      pos_y: { unit: 1, addr: 48, dtype: int32,  confirm: true }
      pos_z: { unit: 1, addr: 49, dtype: int32,  confirm: true }
      ang_u: { unit: 1, addr: 50, dtype: int32,  confirm: true }
      ang_v: { unit: 1, addr: 51, dtype: int32,  confirm: true }
      ang_w: { unit: 1, addr: 52, dtype: int32,  confirm: true }
      j1:    { unit: 1, addr: 56, dtype: int32,  confirm: true }
      j2:    { unit: 1, addr: 57, dtype: int32,  confirm: true }
      j3:    { unit: 1, addr: 58, dtype: int32,  confirm: true }
      j4:    { unit: 1, addr: 59, dtype: int32,  confirm: true }
      j5:    { unit: 1, addr: 60, dtype: int32,  confirm: true }
      j6:    { unit: 1, addr: 61, dtype: int32,  confirm: true }

    robot2:
      running:      { unit: 1, addr: 200, dtype: uint16, confirm: true }
      stack_count:  { unit: 1, addr: 201, dtype: uint16, confirm: true }
      alarm_code:   { unit: 1, addr: 202, dtype: uint16, confirm: true }
      pos_x:        { unit: 1, addr: 203, dtype: int32,  confirm: true }
      pos_y:        { unit: 1, addr: 205, dtype: int32,  confirm: true }
      pos_z:        { unit: 1, addr: 207, dtype: int32,  confirm: true }
      ang_u:        { unit: 1, addr: 209, dtype: int32,  confirm: true }
      ang_v:        { unit: 1, addr: 211, dtype: int32,  confirm: true }
      ang_w:        { unit: 1, addr: 213, dtype: int32,  confirm: true }
      j1:           { unit: 1, addr: 215, dtype: int32,  confirm: true }
      j2:           { unit: 1, addr: 217, dtype: int32,  confirm: true }
      j3:           { unit: 1, addr: 219, dtype: int32,  confirm: true }
      j4:           { unit: 1, addr: 221, dtype: int32,  confirm: true }
      j5:           { unit: 1, addr: 223, dtype: int32,  confirm: true }
      j6:           { unit: 1, addr: 225, dtype: int32,  confirm: true }
