opc_nodes:
  read:                                 # importante manteenr el orden de estos elementos ya que asi empieza la suscripcion de nodos
    start_button:
      #node_id: "ns=2;s=StartBit"
      node_id: "ns=4;i=20"
      type: "method"
      name: "start_button"
    pause_button: 
      # node_id: "ns=2;s=PauseBit"
      node_id: "ns=4;i=21"
      type: "method"
      name: "pause_button"
    stop_button: 
      # node_id: "ns=2;s=StopBit"
      node_id: "ns=4;i=22"
      type: "method"
      name: "stop_button"
    clear_alarm_button: 
      # node_id: "ns=2;s=CleanAlarm"
      node_id: "ns=4;i=23"
      type: "method"
      name: "clear_alarm_button"
    resume_button: 
      # node_id: "ns=2;s=CleanAlarm"
      node_id: "ns=4;i=53"
      type: "method"
      name: "resume_proceso_01"
    test_bit: 
      # node_id: "ns=2;s=CleanAlarm"
      node_id: "ns=4;i=27"
      type: "method"
      name: "proceso_03"
    jog_z: 
      # node_id: "ns=2;s=CleanAlarm"
      node_id: "ns=4;i=38"
      type: "method"
      name: "proceso_04"
    standby: 
      # node_id: "ns=2;s=CleanAlarm"
      node_id: "ns=4;i=37"
      type: "method"
      name: "proceso_05"
    gripper_off: 
      # node_id: "ns=2;s=CleanAlarm"
      node_id: "ns=4;i=50"
      type: "method"
      name: "proceso_06"
    send_data: 
      # node_id: "ns=2;s=SendData"
      node_id: "ns=4;i=24"
      type: "proceso"
      val: 0
    long_caja: 
      # node_id: "ns=2;s=LongCaja"
      node_id: "ns=4;i=3"
      type: "data"
      val: 0
    ancho_caja: 
      # node_id: "ns=2;s=AnchoCaja"
      node_id: "ns=4;i=2"
      type: "data"
      val: 0
    altura_caja:
      node_id: "ns=4;i=14"
      type: "data"
      val: 0
    long_barra:
      # node_id: "ns=2;s=LongBarra"
      node_id: "ns=4;i=8"
      type: "data"
      val: 0
    ancho_barra: 
      # node_id: "ns=2;s=AnchoBarra"
      node_id: "ns=4;i=7"
      type: "data"
      val: 0
    espesor: 
      # node_id: "ns=2;s=Espesor"
      node_id: "ns=4;i=9"
      type: "data"
      val: 0
    peso:
      # node_id: "ns=2;s=Peso"
      node_id: "ns=4;i=13"
      type: "data"
      val: 0
    cantidad_x: 
      # node_id: "ns=2;s=Cantidad_x"
      node_id: "ns=4;i=12"
      type: "data"
      val: 0
    cantidad_z: 
      # node_id: "ns=2;s=Cantidad_z"
      node_id: "ns=4;i=17"
      type: "data"
      val: 0
    no_carro:
      # node_id: "ns=2;s=NoCarro"
      node_id: "ns=4;i=18"
      type: "data"
      val: 0
    w1:
      node_id: "ns=4;i=43"
      type: "data"
      val: 0
    w2:
      node_id: "ns=4;i=47"
      type: "data"
      val: 0
    velocidad: 
      # node_id: "ns=2;s=Velocidad"
      node_id: "ns=4;i=18"
      type: "data"
      val: 0
    bit_voltear:
      # node_id: "ns=2;s=bit_voltear"
      node_id: "ns=4;i=25"
      type: "bridge"
      name: "modify_output_y"
      param: 
        output_id: "40"
        value: false
    bit_stack:
      # node_id: "ns=2;s=bit_stack"
      node_id: "ns=4;i=26"
      type: "bridge"
      name: "modify_output_y"
      param: 
        output_id: "42"
        value: false
    # bit_libre:
    #   node_id: "ns=2;s=bit_libre"
    #   type: "bridge"
    #   name: "modify_output_y"
    #   param: 
    #     output_id: "43"
    #     value: false
  write:
    robot1:
      # running: "ns=2;s=01_Running"
      running: "ns=4;i=29"
      terminado: "ns=4;i=41"
      set_ok: "ns=4;i=28"
      # stack_count: "ns=2;s=01_StackCount"
      stack_count: "ns=4;i=32"
      stack_ready: "ns=4;i=51"
      layer_ready: "ns=4;i=52"
      # alarm_code: "ns=2;s=01_AlarmCode"
      alarm_code: "ns=4;i=33"
      pos_x: "ns=5;i=47"
      pos_y: "ns=5;i=48"
      pos_z: "ns=5;i=49"
      ang_u: "ns=5;i=50"
      ang_v: "ns=5;i=51"
      ang_w: "ns=5;i=52"
      j1: "ns=5;i=56"
      j2: "ns=5;i=57"
      j3: "ns=5;i=58"
      j4: "ns=5;i=59"
      j5: "ns=5;i=60"
      j6: "ns=5;i=61"
    robot2:
      running: "ns=2;s=02_Running"
      stack_count: "ns=2;s=02_StackCount"
      alarm_code: "ns=2;s=02_AlarmCode"
      pos_x: "ns=2;s=02_PosX"
      pos_y: "ns=2;s=02_PosY"
      pos_z: "ns=2;s=02_PosZ"
      ang_u: "ns=2;s=02_AngU"
      ang_v: "ns=2;s=02_AngV"
      ang_w: "ns=2;s=02_AngW"
      j1: "ns=2;s=02_J1"
      j2: "ns=2;s=02_J2"
      j3: "ns=2;s=02_J3"
      j4: "ns=2;s=02_J4"
      j5: "ns=2;s=02_J5"
      j6: "ns=2;s=02_J6"
